config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :movies, only: [:show]
  root to: 'lists#index'

  resources :lists, except: %i[edit update] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  # validates_uniqueness_of :movie, :list, scope: [:bookmark, :id]
  validates :movie, uniqueness: { scope: :list }
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true

  def color
    if rating < 4
      '#F8333C'
    elsif rating < 7
      '#FCAB10'
    else
      '#44AF69'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @movies = Movie.where.not(id: @list.movies).order(title: :asc)
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(strong_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      @movies = Movie.where.not(id: @list.movies).order(title: :asc)
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def strong_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]

  def index
    @list = List.new
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(strong_params)
    if @list.save
      redirect_to lists_path
    else
      @lists = List.all
      render :index
      # render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def strong_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="d-flex justify-content-center">
  <div class="col-12 col-sm-8 col-md-6 col-xl-4 col-xxl-4">
    <div class="container card bg-light py-3">
      <h3 class='my-4 text-center'><strong>Add a movie 🎬</strong></h3>
      <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.association :movie, collection: @movies, include_blank: false %>
          <%= f.input :comment %>
          <%= f.submit class: 'btn btn-info mt-3 w-100' %>
      <% end %>
      <%= link_to "↩ Back", lists_path, class: 'btn btn-outline-dark mt-3' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watch list</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('favicon.svg') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'my-5 w-100 btn btn-info' %>
<% end %>

app/views/lists/index.html.erb
  <div class="d-flex justify-content-center my-5">
    <h1><strong>[Watch list]</strong></h1>
  </div>
  <%# <%= link_to "📃 Add list", new_list_path, class: 'btn btn-dark mb-3 ms-4' %>
<div class="mx-3 row justify-content-center">


  <div class="cards col-12 col-sm-12 col-md-8 col-lg-8 col-xl-9 col-xxl-9 mb-3">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : "https://source.unsplash.com/random/?movie,#{list.name}" %>)">
        <%= link_to '', list_path(list), class: 'list-card-link' %>
        <span><%= list.name %></span>
        <%= link_to '✖', list_path(list), method: :delete, data: {confirm: "Are you sure you want to delete #{list.name}"}, class: 'delete-btn' %>
      </div>
    <% end %>
  </div>

  <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-3 col-xxl-3 card bg-light sticky-top" style="height: 376px">
    <h3 class='my-4 text-center'><strong>Add your list 📝</strong></h3>
    <%= render 'form' %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="d-flex justify-content-center">
  <div class="container col-12 col-sm-10 col-md-10 col-xl-8 col-xxl-6">
    <h1>Add your list</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="d-flex justify-content-center my-5">
  <h1><strong>[<%= @list.name %>]</strong></h1>
</div>
<div class="mx-3 row justify-content-center">
  <%= link_to "Add movie to this list 💬", new_list_bookmark_path(@list), class: 'btn btn-info mb-3' %>
  <div class="cards">
    <% @list.movies.each_with_index do |movie, index| %>
      <div class="card-movie" style="background-image: linear-gradient(rgba(0, 0, 0, 0) 20%, rgba(0, 0, 0, 0.8) 100%), url(<%= movie.poster_url %>)">
        <%= link_to '✖', bookmark_path(@list.bookmark_ids[index]), method: :delete, data: {confirm: "Are you sure you want to delete #{movie.title}"}, class: 'delete-btn' %>
        <div class="rating">
          <h3 style="border-radius: 20px 0 0 20px; background-color: <%= movie.color %>">★ <%= movie.rating %></h3>
        </div>
        <% comment = movie.bookmarks.where(list: @list).first.comment %>
        <p class="comment">"<%= comment.size < 30 ? comment : comment.slice(0..30) + '...' %>"</p>
        <div class="movie-description">
          <h2><%= movie.title %></h2>
          <p><%= movie.overview.slice(0..140) %>...</p>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "↩ Back", lists_path, class: 'btn btn-outline-dark my-3' %>
</div>